<a href="https://colab.research.google.com/github/darghan/R_models_and_statistics/blob/main/numpypandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Comenzando con Numpy


In [1]:
# cargando la librería y chequeando su versión
import numpy as np
np.__version__


'1.21.6'

In [4]:
#crea una lista con números del 0 al 9
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
#convertir enteros en cadenas - este estilo de manipulación de listas se conoce como comprensión de listas.
#La comprensión de listas ofrece una forma versátil de manejar tareas de manipulación de listas fácilmente.  
[str(c) for c in L]

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [7]:
[type(elemento) for elemento in L]

[int, int, int, int, int, int, int, int, int, int]

In [11]:
#crear matrices
import numpy as np
np.zeros(10, dtype='int')


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
#crear una matriz de 3 filas x 5 columnas
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
#crear una matriz con un valor predefinido
np.full((3,5),1/2)

array([[0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5]])

In [15]:
#crear un array con una secuencia establecida
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
#crear un array de espacio par entre el rango de valores dado
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
#crear una matriz 3x3 con media 0 y desviación típica 1 en una dimensión dada
np.random.normal(0, 1, (3,3))

array([[-0.15800505, -0.10361306,  0.58817599],
       [-0.26363595,  0.68545021, -1.63380817],
       [ 1.73092443, -0.23132168, -0.01183245]])

In [18]:
#crear una matriz identidad
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
#establecer una semilla aleatoria
np.random.seed(0)

In [28]:
x1 = np.random.randint(10, size=6) #1-dimension
x2 = np.random.randint(10, size=(3,4)) #2-dimension
x3 = np.random.randint(10, size=(2,3,4)) #3-dimension
print('mi vector:',x1)
print('mi matriz:',x2)
print('mi arreglo:',x3)

mi vector: [5 0 4 1 1 6]
mi matriz: [[6 0 2 3]
 [7 9 2 4]
 [9 0 6 9]]
mi arreglo: [[[2 4 7 3]
  [0 5 4 0]
  [2 3 1 7]]

 [[1 3 4 1]
  [7 4 0 2]
  [7 4 0 2]]]


In [29]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim: 3
x3 shape: (2, 3, 4)
x3 size:  24


In [30]:
x1 = np.array([4, 3, 4, 4, 8, 4])
x1


array([4, 3, 4, 4, 8, 4])

In [31]:
# seleccionando primer elemento
x1[0]

4

In [32]:
#seleccionando el quinto
x1[4]

8

In [ ]:
#seleccionando el último
x1[-1]

In [ ]:
#seleccionando el penúltimo
x1[-2]

In [35]:
# en un arreglo
x2= np.array([[3, 7, 5, 5],[0, 1, 5, 9],[3, 0, 5, 0]])
x2

array([[3, 7, 5, 5],
       [0, 1, 5, 9],
       [3, 0, 5, 0]])

In [36]:
#primera fila y segunda columna
x2[2,3]

0

In [37]:
#3ª fila y último valor de la última columna
x2[2,-1]

0

In [38]:
#reemplazar valor en índice 0,0 por 12
x2[0,0] = 12

In [50]:
#desde el inicio hasta la 4ª posición
x3 = np.arange(12)
x3[:5]

array([0, 1, 2, 3, 4])

In [43]:
#desde la 4ª posición hasta el final
x3[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
#de la 4ª a la 6ª posición
x3[4:7]

array([4, 5, 6])

In [45]:
#devolver elementos en lugares pares
x3[ : : 2]

array([ 0,  2,  4,  6,  8, 10])

In [47]:
#devolver elementos desde la primera posición en paso de dos
x3[1::2]

array([ 1,  3,  5,  7,  9, 11])

In [49]:
#invertir el arreglo
x3[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [51]:
num = []
num.append(10)
num.append(5)
num.append(3)
print(num)

[10, 5, 3]


In [52]:
type(num)

list

In [55]:
arreglo=np.array(num)

In [56]:
type(arreglo)

numpy.ndarray

In [57]:
#Puedes concatenar dos o más arrays a la vez.
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [21,21,21]
np.concatenate([x, y,z])

array([ 1,  2,  3,  3,  2,  1, 21, 21, 21])

In [58]:
#También puedes usar esta función para crear matrices bidimensionales.
rejilla = np.array([[1,2,3],[4,5,6]])
np.concatenate([rejilla,rejilla])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [59]:
#Usando su parámetro axis, puedes definir matrices por filas o columnas
np.concatenate([rejilla,rejilla],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [60]:
y = np.array([3,4,5])
grid = np.array([[1,2,3],[17,18,19]])
np.vstack([y,grid])

array([[ 3,  4,  5],
       [ 1,  2,  3],
       [17, 18, 19]])

In [61]:
#De forma similar, puedes añadir un array usando np.hstack
z = np.array([[9],[9]])
np.hstack([grid,z])

array([[ 1,  2,  3,  9],
       [17, 18, 19,  9]])

In [97]:
w = np.random.randint(12, size=18) #1-dimension
print(np.average(w))
print(np.amax(w))
print(np.amin(w))
print(np.var(w))
print(np.unique(w))
print(np.sum(w))
print(np.std(w))
print(np.split(w,3))
print(np.sort(w))
print(np.size(w))
print(np.shape(w))
print(np.tan(w))
print(np.square(w))
print(np.quantile(w,0.50))
print(np.nanmedian(w))
print(np.percentile(w, 25))
print(np.prod(w))
print(np.cumsum(w))
print(np.diff(w))
print(np.exp(w))
print(np.exp2(w))
print(np.log(w+1))
print(np.log10(w+1))
print(np.log2(w+1))
print(np.log1p(w))

4.166666666666667
11
0
13.805555555555555
[ 0  1  2  4  6  7  9 10 11]
75
3.7155828016013257
[array([ 7, 11,  2,  4,  1,  1]), array([ 1,  7,  9,  0,  9, 10]), array([0, 2, 1, 4, 6, 0])]
[ 0  0  0  1  1  1  1  2  2  4  4  6  7  7  9  9 10 11]
18
(18,)
[   0.87144798 -225.95084645   -2.18503986    1.15782128    1.55740772
    1.55740772    1.55740772    0.87144798   -0.45231566    0.
   -0.45231566    0.64836083    0.           -2.18503986    1.55740772
    1.15782128   -0.29100619    0.        ]
[ 49 121   4  16   1   1   1  49  81   0  81 100   0   4   1  16  36   0]
3.0
3.0
1.0
0
[ 7 18 20 24 25 26 27 34 43 43 52 62 62 64 65 69 75 75]
[  4  -9   2  -3   0   0   6   2  -9   9   1 -10   2  -1   3   2  -6]
[1.09663316e+03 5.98741417e+04 7.38905610e+00 5.45981500e+01
 2.71828183e+00 2.71828183e+00 2.71828183e+00 1.09663316e+03
 8.10308393e+03 1.00000000e+00 8.10308393e+03 2.20264658e+04
 1.00000000e+00 7.38905610e+00 2.71828183e+00 5.45981500e+01
 4.03428793e+02 1.00000000e+00]
[1.280e+0